### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [dikiaap/ama#3]

**Comment by dikiaap** [comment]
I love learning projects such as [freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp), [open-source-society](https://github.com/ossu/computer-science), and kind of awesome list. Because this list helps me learn more about programming.

**Edit:** This is my opinion from 2015, it may have changed.

**Comment by yosbelms** [comment]
I prefer ([yosbelms/cor](https://github.com/yosbelms/cor)) the one I take care of. It is programming languge that compiles to javascript, a young but serious project.

But I watch [tastejs/todomvc](https://github.com/tastejs/todomvc) very closely, it is kind of show room of front-end application-oriented development frameworks. It is a good help to make a choice.
