### ISSUE TITLE
Which successful startup do you wish you could have created and why?

### ISSUE THREAD

**Issue by CarlMungazi** [dikiaap/ama#4]

**Comment by dikiaap** [comment]
Ok, good question.

I'm young, but I want to donate now.
In the future, I will make a useful company public. This imagination and dreams, but hopefully will be achieved. Such as hospitals with advanced technology, to fund the war for the good of people and make safe, makes a big farm and beautiful environment and comfortable in old age to play with the family.

The possibility of several years, I will try to make the startup of the environment and technology. Because I will make the startup for society, all will be best for him.
